language: php

php:
    - 7.0

before_install:
    - composer self-update
    - composer install --verbose --prefer-source --no-interaction -o

script:
    - ./vendor/bin/phpcs --standard=tests/phpcs.xml --ignore=*PhueServiceProvider*,*LightFinder* library/
    - ./vendor/bin/phpunit --configuration=tests

notifications:
    email: false

sudo: false
